### ISSUE TITLE
iGPU support for N6005

### ISSUE THREAD

**Issue by xavier-thomas** [PeterSuh-Q3/tinycore-redpill#18]
Hi Peter,

First of all, thank you very much for all the great work you've done.
I'm trying to use a bare metal Intel N6005 board to run a plex host and I can't get HW Transcoding to work.

The `/dev/dri` device is not found.

Is this a missing driver issue ? and if so is there a way to package the drivers and enable the iGPU ?

I'm a complete new comer to this and would like some help to get pointed in the right direction.

everything else about the system is super stable and  DSM 7.2 runs very well on it, so it would be superb if I can get the iGPU enabled.

**Comment by PeterSuh-Q3** [comment]
Hi Thomas.

Thank you for your sponsor donation.

In N6005 Jasper Lake, existing Synology models DS918+, DS920+, etc. cannot use iGPU acceleration for transcoding.

SA6400, which uses the newly developed and stabilized kernel 5, is the only solution.

The advantage of this model is the same Device-Tree as DS920+, which allows for easy device automatic mapping.
And, it even supports HBAs.

As you know, plex pass is required for HW transcoding.
However, SA6400, with Kernel 5's fast transcoding processing ability, has excellent processing ability even if it is SW transcoding.
Compared to existing models, the CPU load is relatively very low.

And, SA6400 does not need SYNO genuine SN or AME patches, which were required for existing models.

After installing DSM, check whether the /dev/dri directory exists and
dmesg | All you have to do is check whether the i915 module has been loaded without any problems using grep i915, etc.

**Comment by xavier-thomas** [comment]
Hi @PeterSuh-Q3 thank you for the reply.

I tried to do as you suggested and followed the instructions to set up my device as a SA6400. 

I am able to use tinycore to build the Friend and reboot. However, once the friend loads, it gets an ip, goes into the boot phase and then the screen then goes completely blank but the box is still running. I tried waiting for around 15 - 20 minutes and trying `find.synology.com` but the device is not detected at all. 

It looks like the friend bootloader crashed.
Any idea what the problem is ?

I'm using a Topton n6005 motherboard.
When I tried setting it up as a DS920 earlier, it was working perfectly.

**Comment by PeterSuh-Q3** [comment]
I searched for topton N6005 on AliExpress.
Is the product below correct?

https://www.aliexpress.com/item/1005004761498719.html

The NIC chipset shown in the product specifications is Intel i226-v.

This chipset has had issues with various OSes.

For Windows, Intel proactively supplemented drivers, but

The case of Linux is a little different.

You must verify stability after patching all i226-v modules corresponding to each kernel.

In the case of TCRP-mshell, stabilization testing is in progress.

In the case of TCRP-mshell, three kernels are used.

Tinycore Linux kernel, which corresponds to the first menu-based screen,
2nd Friend kernel,
3rd DSM kernel

All igc modules running the i226-v chipset in these three kernels must operate normally.

This test is scheduled for today with a Korean user using i226-v.
We are going to test it on DS918+ and SA6400 models.

There was an issue with the first Tinycore Linux version 12.x kernel, which prevented i226-v from operating.

It seems like you are in a slightly different situation in that you passed this part.

Also, I thought it would be a good idea to test it myself with the i226-v chipset, so I purchased the same NIC from AliExpress and it is currently being delivered quickly.

This is because there are limits to requesting testing through users.

We will conduct a test with Korean users scheduled for today and notify you when stability is confirmed.

**Comment by PeterSuh-Q3** [comment]
A while ago, the friend kernel was updated from 0.1.0 to 0.1.0a.

![스크린샷 2023-12-18 오전 12 16 54](https://github.com/PeterSuh-Q3/tinycore-redpill/assets/85427533/88f5bf9b-6773-4813-a60e-d50ad0b05b60)

Now you can visually see all four IP addresses.
With a visible IP address other than find.synology.com

Try a ping test first in advance.
IP Address: 5000 Please test direct connection.
Please feed back the results.

**Comment by xavier-thomas** [comment]
Yes, that's the correct motherboard.

I'll try the process again and try recording / screen capture for you so it will help.

**Comment by xavier-thomas** [comment]
Good news. I ran through the install process again and somehow it managed to complete the installation.
`/dev/dri` exists and i've passed it through to plex and tested that HW transcoding works.

<img width="1128" alt="Screenshot 2023-12-17 at 21 41 15" src="https://github.com/PeterSuh-Q3/tinycore-redpill/assets/38254298/9299cdac-3054-4e43-b15c-1ab8f20e116a">
<img width="373" alt="Screenshot 2023-12-17 at 22 45 16" src="https://github.com/PeterSuh-Q3/tinycore-redpill/assets/38254298/a9e4648a-cd3f-45d5-9153-602854fb8ed6">

**Comment by PeterSuh-Q3** [comment]
Thank you for your feedback.
Transcoding works as expected.

However, yesterday, in the feedback from a user in Korea using a similar AliExpress sales model as yours, a problem was reported in which three NICs out of four i226-v (igc modules) could not be woken up again after being converted to EEE (Energy Efficient Ethernet) state. received.

Among the igc modules I compiled and the rr version of the modules, I am looking for modules for which stability has been established.
I think it would be a good idea to check this part one more time.
Currently, the igc module compiled directly by mshell is used in v1.64.
https://github.com/PeterSuh-Q3/arpl-modules/releases/tag/v1.64

**Comment by everwisher** [comment]
I'm curious if AlderLake processors like N100 has a chance of getting HW acceleration with the SA6400 model profile?

**Comment by PeterSuh-Q3** [comment]
> I'm curious if AlderLake processors like N100 has a chance of getting HW acceleration with the SA6400 model profile?

Yes, it is possible.
Recently, @MoetaYuko developed the i915 module for stable and fast transcoding HW acceleration in SA6400.
The first environment he tested was N100, Jellyfin.

**Comment by everwisher** [comment]
> > I'm curious if AlderLake processors like N100 has a chance of getting HW acceleration with the SA6400 model profile?
> 
> Yes, it is possible. Recently, @MoetaYuko developed the i915 module for stable and fast transcoding HW acceleration in SA6400. The first environment he tested was N100, Jellyfin.

Thank you for letting me know his work. I've succeeded in getting his driver working on a physical xpenology.
