### ISSUE TITLE
no internet after booting up

### ISSUE THREAD

**Issue by dufka66** [PeterSuh-Q3/tinycore-redpill#20]
Hi PeterSuh-Q3,

Firstly i really appreciate the work thank you for that!

I have an issue with the loader. Once it loads i see a purple line rops_handle_POLLIN: DELADDR and then the UTP link from the back goes off and i dont have any connection to the IP anymore. Attached a screenshot. Thanks again for the support.

Kind regards
![WhatsApp Image 2023-12-20 at 15 52 46](https://github.com/PeterSuh-Q3/tinycore-redpill/assets/154445689/0672d76e-f217-4c4d-91df-2b98a1e0078e)

**Comment by PeterSuh-Q3** [comment]
It has not yet been revealed that the "rops_handle_POLLIN: DELADDR" message is directly related to the UTP Link being turned off. In most cases, the NIC operates normally despite the above message.

If this is your first time using Redpill, your NIC may have some special features.

Can you go back to the TCRP Loader Build menu, download all the files in the directory below, and attach them to the issue here?
Let us analyze the log.
/mnt/sda1/logs/jr

![스크린샷 2023-12-21 오전 10 29 05](https://github.com/PeterSuh-Q3/tinycore-redpill/assets/85427533/16c04700-b129-4b90-964b-0319ccb253c4)

**Comment by dufka66** [comment]
Hi Peter,

Thnx for the quick reply. Problem is i dont have a folder logs where i can troubleshoot. I have been running redpill for some time now but on a proxmox VM but now i want to move to a baremetal so i can use all the resources for XPE. Here is a screenshot of my /mnt/sda1 folder 

![image](https://github.com/PeterSuh-Q3/tinycore-redpill/assets/154445689/1ac16b90-8f6c-486a-85c6-ce0dd283be32)

![image](https://github.com/PeterSuh-Q3/tinycore-redpill/assets/154445689/ed0a0af4-88f5-4fd3-be18-e1e4b73b541d)

Kind regards

**Comment by PeterSuh-Q3** [comment]
Does Nvme also have TCRP bootloader content?
I don't think I've ever written a script to mount Nvme.
The two partitions of nvme appear to be mounted.
What is this nvme for and what does it contain?

**Comment by PeterSuh-Q3** [comment]
In very rare cases, nvme may prevent the Friend kernel from booting.
In the case of the ASUS IOT H310i-IM-A R2.0 motherboard I use, M.2 Nvme cannot be used as storage.
This is a case where an infinite error occurs in the kernel and the kernel panics.
I'm not sure what NVME is for, but would you try booting with it removed?

**Comment by dufka66** [comment]
Tested withouth the nvme and same behaviour ethernet port lamp goes out after the comment and no log folder once i boot back to build. Any other suggestions its driving me nuts.

**Comment by PeterSuh-Q3** [comment]
Without dmesg or linuxrc.syno.log, it is difficult to analyze the cause.

If the nic does not work, the COM1 serial port can take over this role, 
but it is difficult for ordinary users to have this environment.

So, the last suggestion seems to be to install another Intel-based NIC separately instead of the r8169 Realtek NIC.
